import { Printer } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { money, formatDate } from "@/lib/format";
import { printElement } from "@/lib/exportCsv";

export interface ReceiptData {
  receiptNumber: string;
  title: string;
  tenant: string;
  property: string;
  room: string;
  amount: number;
  date: string;
  method: string;
  reference?: string | null;
  description?: string | null;
}

export function ReceiptDialog({
  receipt,
  onOpenChange,
}: {
  receipt: ReceiptData | null;
  onOpenChange: (open: boolean) => void;
}) {
  if (!receipt) return null;

  const rows: [string, string][] = [
    ["Receipt number", receipt.receiptNumber],
    ["Tenant", receipt.tenant],
    ["Property", receipt.property],
    ["Room", receipt.room],
    ["Payment date", formatDate(receipt.date)],
    ["Method", receipt.method.replace("_", " ")],
    ["Reference", receipt.reference || "—"],
    ["Description", receipt.description || receipt.title],
  ];

  function print() {
    const html = `
      <h1>NyumbaPro</h1>
      <div class="muted">${receipt!.title} receipt</div>
      <table>${rows.map(([k, v]) => `<tr><td>${k}</td><td>${v}</td></tr>`).join("")}
      <tr><td class="total">Amount</td><td class="total">${money(receipt!.amount)}</td></tr></table>
      <p class="muted" style="margin-top:24px">Generated by NyumbaPro · ${new Date().toLocaleString("en-TZ")}</p>`;
    printElement(html, receipt!.receiptNumber);
  }

  return (
    <Dialog open onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>{receipt.title} receipt</DialogTitle>
        </DialogHeader>
        <div className="rounded-xl bg-secondary/40 p-5 ring-1 ring-border">
          <div className="flex items-center gap-2">
            <div className="grid size-7 place-items-center rounded-md bg-primary font-display text-sm font-bold text-primary-foreground">
              N
            </div>
            <span className="font-display text-[13px] font-semibold">NyumbaPro</span>
          </div>
          <dl className="mt-4 space-y-2 text-[13px]">
            {rows.map(([k, v]) => (
              <div key={k} className="flex justify-between gap-4">
                <dt className="text-muted-foreground">{k}</dt>
                <dd className="text-right">{v}</dd>
              </div>
            ))}
            <div className="flex justify-between gap-4 border-t border-border pt-3">
              <dt className="font-display font-medium">Amount</dt>
              <dd className="ledger-num font-display text-lg font-semibold">{money(receipt.amount)}</dd>
            </div>
          </dl>
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Close
          </Button>
          <Button onClick={print}>
            <Printer className="size-4" /> Print / save PDF
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
